FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Define build arguments
ARG SUPABASE_URL
ARG SUPABASE_PUBLIC_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG JWT_SECRET

# Set environment variables
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_PUBLIC_KEY=$SUPABASE_PUBLIC_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV HOST=0.0.0.0
ENV PORT=8080

RUN npm run build

EXPOSE 8080

CMD ["node", "./dist/server/entry.mjs"]
